# BEGIN
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# END
